# Generated by Django 3.2.12 on 2022-05-25 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_name', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=100)),
                ('seats', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=300)),
                ('destination', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Routes',
                'verbose_name_plural': 'Routes',
            },
        ),
        migrations.CreateModel(
            name='Sacco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('full', models.BooleanField(default=False)),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qrcode')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cars')),
                ('routes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route')),
            ],
            options={
                'verbose_name': 'Schedules',
                'verbose_name_plural': 'Schedules',
            },
        ),
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('fare', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('confirm', models.BooleanField(default=False)),
                ('schedules', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.schedules')),
            ],
            options={
                'verbose_name': 'Passengers',
                'verbose_name_plural': 'Passengers',
            },
        ),
        migrations.AddField(
            model_name='cars',
            name='sacco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.sacco'),
        ),
    ]
