# Generated by Django 3.2.12 on 2022-05-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_passengers_schedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
