# Generated by Django 3.2.12 on 2022-05-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_passengers_fare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
