# Generated by Django 3.2.12 on 2022-05-25 18:49

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_schedules_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedules',
            name='date_time',
        ),
        migrations.AddField(
            model_name='schedules',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedules',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 5, 25, 18, 49, 57, 837480, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
